# spring boot configuration:
spring:
  datasource:
    url: jdbc:mysql://localhost/exchange?useSSL=false
    username: root
    password:
    hikari:
      pool-name: HikariCP
      auto-commit: false
      connection-timeout: 5000
      max-lifetime: 600000
      maximum-pool-size: 50
      minimum-idle: 5
  jpa:
      show-sql: true
      database: mysql
      generate-ddl: true

logging:
  level:
    com.itranswarp.warpdb.WarpDb: DEBUG
